/*
 * This source file was generated by the Gradle 'init' task
 */
package ies.pedro;

import ies.pedro.components.*;
import ies.pedro.components.Block;
import ies.pedro.components.dialogs.DialogBackground;
import ies.pedro.components.dialogs.DialogTime;
import ies.pedro.model.*;
import ies.pedro.utils.ImageWithPath;
import ies.pedro.utils.Size;
import jakarta.xml.bind.JAXBException;

import java.io.File;
import java.io.IOException;

import java.net.URISyntaxException;
import java.security.Principal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Optional;

import java.util.logging.Logger;

import javafx.application.Application;
import javafx.application.Platform;


import javafx.geometry.Point2D;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;


import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;

import javafx.scene.control.SeparatorMenuItem;
import javafx.scene.image.Image;
import javafx.scene.layout.BorderPane;

import javafx.scene.layout.Pane;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

public class App extends Application {


    Scene scene;
    public static int SCALE = 3;
    public static int CELLWIDTH = 8;
    public static int CELLHEIGHT = 8;
    private final int width = 224 * SCALE;
    private final int height = 240 * SCALE;

    private EditorCanvas editor;
    private MediaPlayer mp;
    private LevelsPanel levelsPanel;
    private Levels levels;


    public App() {
        super();
        try {
            Block.loadBlocks("assets/blocks.json");
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
        this.levels = new Levels();

    }
    @Override
    public void start(Stage stage) {
        BorderPane border = new BorderPane();
        border.setCenter(this.createEditor());

        border.setLeft(this.createBlockMenu());
        border.setRight(this.levelsPanel = this.createLevelPanel());
        border.setTop(this.createMenu());
        this.scene = new Scene(border, this.width + 330, this.height + 50);
        stage.setTitle("DAM Editor");
        stage.getIcons().add(new Image(String.valueOf(App.class.getResource("/icono.png"))));
        stage.setResizable(false);
        stage.setScene(scene);
        //para que cierre al pulsar el icono
        stage.setOnCloseRequest(t -> {
            Platform.exit();
            System.exit(0);
        });
        stage.show();
        this.editor.draw();
    }

    /**
     * Crea el panel lateral de bloques
     */
    private ElementsPanel createBlockMenu() {
        HashMap<String,ArrayList<Block>> map = new HashMap<>();
        Block.getGroups().forEach(group -> {
            ArrayList<Block> blocks = new ArrayList<>();
            String [] nombres= Block.getNamesBlocksByGroup(group);
            for (String nombre : nombres) {
                Block tb = new Block(group,nombre);
                blocks.add(tb);
                switch (tb.getType()) {
                    case "Borrador":
                        tb.addClickListener(() -> {
                            this.editor.changMode(EditorCanvas.MODO_EDITOR.DELETE);
                        });
                        break;
                    case "Puntero":
                        tb.addClickListener(() -> {
                            this.editor.changMode(EditorCanvas.MODO_EDITOR.NONE);
                        });
                        break;
                    default:
                        Block finalTb = tb;
                        tb.addClickListener(() -> {
                            this.editor.changMode(EditorCanvas.MODO_EDITOR.ADD);
                            this.editor.setBlock(finalTb);
                        });
                }
            }
            map.put(group,blocks);

        });
        ElementsPanel ep= new ElementsPanel(map);
        return ep;
    }

    /**
     * crea el editor de nivels
     *
     */
    private EditorCanvas createEditor() {
        this.editor = new EditorCanvas();
        this.editor.init();
        return this.editor;
    }

    /**
     * crea el panel de niveles, con lista de niveles, botones administración y música
     *
     */
    private LevelsPanel createLevelPanel() {
        LevelsPanel levelspanel = new LevelsPanel();
        levelspanel.init();
        levelspanel.setOnadd((s) -> {
            Level l = new Level(s.getName(), s.getSize());

            l.setSize(s.getSize());
            l.init();
            this.levels.addLevel(l);
            this.levels.setSelected(l.getName());
            this.editor.setLevel(l);
            this.deleteMediaplayer();

        });
        levelspanel.setOndelete((s) -> {
            this.levels.removeLevel(s);
            this.deleteMediaplayer();
            this.editor.setLevel(null);

        });
        levelspanel.setOnseleted((s) -> {
            levels.setSelected(s);
            this.deleteMediaplayer();
            this.editor.setLevel(levels.getSelected());

        });

        levelspanel.setOnreset(s ->
        {
            if (this.levels.getSelected() != null) {
                this.levels.resetSelected();
                this.editor.setRepaintbackground(true);
                this.editor.draw();
                this.deleteMediaplayer();
            }
        });
        levelspanel.setOnplay(() -> {
            if (this.levels.getSelected() != null) {
                //si es nulo y existe una cancion
                if ((this.mp == null && this.levels.getSelected().getSound() != null) || (this.mp != null && this.mp.getMedia().getSource() != this.levels.getSelected().getSound())) {
                    this.mp = new MediaPlayer(new Media(new File(this.levels.getSelected().getSound().replace("\\", "//")).toURI().toString()));
                    this.mp.setCycleCount(MediaPlayer.INDEFINITE);
                }
                if (this.mp != null) {
                    this.mp.play();
                }
            }
        });
        levelspanel.setOnpause(() -> {
            if (this.levels.getSelected() != null && this.mp != null) {
                this.mp.pause();
            }
        });

        levelspanel.setOnstop(() -> {
            if (this.levels.getSelected() != null && this.mp != null) {
                this.mp.stop();
            }
        });
        return levelspanel;
    }

    private MenuBar createMenu() {
        MenuBar menuBar = new MenuBar();

        Menu fileMenu = new Menu("File");
        MenuItem newMenuItem = new MenuItem("New");
        newMenuItem.setOnAction(eh -> {
            this.levels.reset();
            this.editor.reset();
            this.levelsPanel.reset();
        });
        MenuItem saveMenuItem = new MenuItem("Save");
        saveMenuItem.setOnAction(actionEvent -> {

            final FileChooser fileChooser = new FileChooser();
            File file = fileChooser.showSaveDialog(scene.getWindow());
            fileChooser.getExtensionFilters().addAll(
                    new FileChooser.ExtensionFilter("XML", "*.xml"),
                    new FileChooser.ExtensionFilter("Json", "*.json"),
                    new FileChooser.ExtensionFilter("Bin", "*.bin")
            );
            if (file != null) {
                try {
                    Level.save(this.levels.getSelected(),file);
                    //Levels.save(this.levels, file);
                } catch (JAXBException ex) {
                    Alert alert = new Alert(AlertType.ERROR);
                    alert.setTitle("Infor error");
                    alert.setHeaderText(null);
                    alert.setContentText(ex.getMessage());
                    ex.printStackTrace();
                    alert.showAndWait();
                    //ex.printStackTrace();
                } catch (Exception ex) {
                    Alert alert = new Alert(AlertType.ERROR);
                    alert.setTitle("Infor error");
                    alert.setHeaderText(null);
                    alert.setContentText(ex.getMessage());
                    ex.printStackTrace();
                    alert.showAndWait();
                    // ex.printStackTrace();
                }
            }

        });
        MenuItem loadMenuItem = new MenuItem("Load");
        loadMenuItem.setOnAction(actionEvent -> {
            final FileChooser fileChooser = new FileChooser();
            fileChooser.getExtensionFilters().addAll(
                    new FileChooser.ExtensionFilter("XML", "*.xml*"),
                    new FileChooser.ExtensionFilter("Json", "*.json"),
                    new FileChooser.ExtensionFilter("Bin", "*.bin")
            );
            File file = fileChooser.showOpenDialog(scene.getWindow());
            if (file != null) {
                try {
                   this.levels= new Levels();
                   this.levels.addLevel(Level.load(file));
                   //para los nives
                   // Levels m = Levels.load(file);
                   // this.levels = m;
                    this.levels.setSelected(0);
                    this.editor.reset();
                    this.editor.setLevel(this.levels.getSelected());
                    this.levelsPanel.reset();
                    this.levelsPanel.setItems(this.levels);

                } catch (IOException ex) {
                    Alert alert = new Alert(AlertType.ERROR);
                    alert.setTitle("Infor error");
                    alert.setHeaderText(null);
                    alert.setContentText(ex.getMessage());
                    ex.printStackTrace();
                    alert.showAndWait();
                } catch (ClassNotFoundException ex) {
                    Alert alert = new Alert(AlertType.ERROR);
                    alert.setTitle("Infor error");
                    alert.setHeaderText(null);
                    alert.setContentText(ex.getMessage());
                    ex.printStackTrace();
                    alert.showAndWait();
                } catch (Exception ex) {
                    Alert alert = new Alert(AlertType.ERROR);
                    alert.setTitle("Infor error");
                    alert.setHeaderText(null);
                    alert.setContentText(ex.getMessage());
                    ex.printStackTrace();
                    alert.showAndWait();
                }

            }

        });
        Menu optionsMenu = new Menu("Options");
        MenuItem soundMenu = new MenuItem("Sound");
        optionsMenu.getItems().add(soundMenu);
        soundMenu.setOnAction(actionEvent -> {
            final FileChooser fileChooser = new FileChooser();
            fileChooser.getExtensionFilters().addAll(
                    new FileChooser.ExtensionFilter("mp3", "*.mp3*")

            );
            File file = fileChooser.showOpenDialog(scene.getWindow());
            if (file != null) {
                this.editor.getLevel().setSound(file.getAbsolutePath());
                if(this.mp!=null)
                this.mp.stop();

            }

        });
        MenuItem backgroundMenu = new MenuItem("Background");
        optionsMenu.getItems().add(backgroundMenu);
        backgroundMenu.setOnAction(actionEvent -> {
            DialogBackground db = new DialogBackground();
            db.setImages(this.loadBackgroundFromDirectory("./assets/backgrounds"));
            db.init();
            Optional<ImageWithPath> result = db.showAndWait();
            if (result.isPresent()) {
                result.get();
                if (this.editor.getLevel() != null) {
                    Image img = result.get().getImage();
                    this.editor.getLevel().setBackgroundPosition(result.get().getPath());
                    //   this.editor.getLevel()..setBackgroundPosition(result.get());
                    this.editor.setRepaintbackground(true);
                    this.editor.draw();
                }
            }
        });


        MenuItem timeMenu = new MenuItem("Time");
        timeMenu.setOnAction(eh -> {
            DialogTime dt = new DialogTime();
            dt.init();
            Optional<Double> result = dt.showAndWait();
            if (result.isPresent()) {
                result.get();
                if (this.editor.getLevel() != null) {
                    this.editor.getLevel().setTime(result.get());
                }
            }


        });
        optionsMenu.getItems().add(timeMenu);

        MenuItem exitMenuItem = new MenuItem("Salir");
        exitMenuItem.setOnAction(actionEvent -> Platform.exit());

        fileMenu.getItems().addAll(newMenuItem, saveMenuItem, loadMenuItem,
                new SeparatorMenuItem(), exitMenuItem);

        menuBar.getMenus().addAll(fileMenu, optionsMenu);//, webMenu, sqlMenu);
        return menuBar;
    }

    private void deleteMediaplayer() {
        if (this.mp != null) {
            this.mp.stop();
            this.mp = null;
        }
    }
    private ArrayList<ImageWithPath> loadBackgroundFromDirectory(String path) {

        ArrayList<ImageWithPath> images = new ArrayList<>();

        return images;
    }
}
