/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}
javafx {
    version = "22.0.1"
    modules = listOf( "javafx.controls", "javafx.graphics", "javafx.fxml", "javafx.media", "javafx.swing" )
}
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
tasks.register<Copy>("copyAssets") {
    from("assets")            // carpeta con imágenes
    //from("config.json")       // fichero JSON
  into(  layout.buildDirectory.dir("assets"))
}
tasks.named("build") {
    dependsOn("copyAssets")
}

tasks.named("run") {
    dependsOn("copyAssets")
}
dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.controlsfx:controlsfx:11.2.1")
    implementation("org.kordamp.ikonli:ikonli-javafx:12.3.1")
    implementation("org.kordamp.ikonli:ikonli-antdesignicons-pack:12.3.1")
    implementation("org.kordamp.ikonli:ikonli-bootstrapicons-pack:12.3.1")
    implementation ("org.kordamp.ikonli:ikonli-fileicons-pack:12.3.1")
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:3.0.1")
    implementation("com.sun.xml.bind:jaxb-impl:3.0.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ies.pedro.App"
}
